import java_cup.runtime.*;

terminal                            INT, DOUBLE, PYC;
terminal String                     IDENT;

non terminal                        sent;
non terminal String                 lista_int, lista_double;

sent ::= INT lista_int:l PYC                {: Test.out.println(l); :}
       | DOUBLE lista_double:l PYC          {: Test.out.println(l); :}
       ;

lista_int ::= IDENT:i lista_int:l {: RESULT = i+":int; "+l; :}
            | IDENT:i {: RESULT = i+":int;"; :}
            ;

lista_double ::= IDENT:i lista_double:l {: RESULT = i+":double; "+l; :}
            | IDENT:i {: RESULT = i+":double;"; :}
            ;
