import java_cup.runtime.*;
import java.util.ArrayList;

terminal String IDENT;
terminal INT, DOUBLE, PYC, COMA, DP;

non terminal programa;
non terminal ArrayList<String> lista;

programa ::= lista:l DP INT PYC          {: for(String s : l) Test.out.print(s+":int;"); :}
           | lista:l DP DOUBLE PYC       {: for(String s : l) Test.out.print(s+":double;"); :}
           ;

lista ::= IDENT:i                  {: RESULT = new ArrayList(); RESULT.add(i); :}
        | lista:l COMA IDENT:i     {: l.add(i); RESULT = l; :}
        ;
