import java_cup.runtime.*;

terminal String IDENT;
terminal INT, DOUBLE, PYC, COMA, DP;

non terminal programa;
non terminal String lista;

programa ::= lista:l INT PYC      {: Test.out.print("int "+l); :}
           | lista:l DOUBLE PYC   {: Test.out.print("double "+l); :}
           ;

lista ::= IDENT:i DP              {: RESULT = i+";"; :}
        | IDENT:i COMA lista:l    {: RESULT = i+","+l; :}  
        ;
